name: Publish docs

on: [ workflow_dispatch, workflow_call ]

jobs:
  pub-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Create clean documentation branch
      run:  git checkout -b documentation

    - name: Install
      run:  sudo apt=get install doxygen

    - name: Install LaTeX extensions
      run:  sudo apt-get install texlive-base texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended

    - name: Install Python modules
      run: sudo apt-get install pip3 install jinja2 Pygments

    - name: Install m.css
      uses: actions/checkout@v3
      with:
        repository: mosra/m.css
        path: m.css

    - name: Generate autodocs for dynmenu
      run:  |
        cd m.css/documetation
        ./doxygen.py ../../Doxyfile

    - name: Add generated autodocs to Git repo in the documentation branch
      run:  |
        git config --global user.email "github-bot@basealt.ru"
        git config --global user.name  "$GITHUB_WORKFLOW GitHub action"
        git add -f docs
        git commit -am "docs: add auto-generated developer documentation"

    - name: Result URLs
      run:  |
        REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
        echo "Documentation on a github.io:  https://$REPO_OWNER.github.io/$REPO_NAME/docs"
        echo ""
        echo "Documentation branch: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/documentation"

